---
driver:
  name: vagrant
  customize:
    memory: 4192
 
provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

# network is only necessary if accessing SmartSense via UI
platforms:
  - name: precise64
    run_list:
       - recipe[java::oracle]
       - recipe[smartsense-chef::default]
    driver:
      box: precise64
      box_url: precise-server-cloudimg-amd64-vagrant-disk1.box
      network:
      - [ "private_network" , { ip : "192.168.33.7" } ]	

suites:
  - name: default
    attributes:
